baseURL = 'https://oshwc.org/'
#relativeURL=true
#canonifyURL=true
#baseURL = 'https://nanbuwks.github.io/oshwc_hugo/'
#canonifyurls=true
publishDir="public"
languageCode = 'ja'
title = 'OSHWC:OpenHardWareConference'
theme = 'ananke'
[[menu.main]]
  identifier = "OSHWC2026Akihabaraspring"
  name = "OSHWC 2026 Akihabara/Spring"
  url = "/posts/oshwc2026akihabaraspring/"
  weight = 10 
[[menu.main]]
  identifier = "OSHWC2026Akihabaraspringentry"
  name = "出展・登壇者向け情報"
  url = "/posts/oshwc2026akihabaraspring4exhivitors/"
  weight = 20
[[menu.main]]
  identifier = "blog"
  name = "blog"
  url = "/posts/"
  weight = 30 
[[menu.main]]
  identifier = "whatisOSHWC"
  name = "OSHWCとは"
  url = "/posts/whatisOSHWC/"
  weight = 40 
[[menu.main]]
  identifier = "aboutus"
  name = "Aboutus"
  url = "/posts/aboutus/"
  weight = 60

[params]
custom_css = ["custom.css"]
